### ISSUE TITLE
Blog about this

### ISSUE THREAD

**Issue by ralphbean** [brendan-w/lzr#1]
Specifically [this](https://imgur.com/a/pBG3L), to the [fedora planet](http://fedoraplanet.org/).  Please?  This is awesome.  Thanks!

**Comment by decause** [comment]
#agreed

:rainbow: :tiger2: :joy:

**Comment by brendanwhitfield** [comment]
Will do! Thanks, glad you guys like it!

I'm going to see if I can't get a good white color out of that laser. The green was on the fritz, which is why it turned pink.

**Comment by brendan-w** [comment]
https://fedoramagazine.org/creating-laser-light-show-with-fedora/
